#ifndef EMMC_CMD_H
#define EMMC_CMD_H

#include "emmc_types.h"

/* eMMC command indices */
#define EMMC_CMD0 0	  /* GO_IDLE_STATE */
#define EMMC_CMD1 1	  /* SEND_OP_COND */
#define EMMC_CMD2 2	  /* ALL_SEND_CID */
#define EMMC_CMD3 3	  /* SET_RELATIVE_ADDR */
#define EMMC_CMD4 4	  /* SET_DSR */
#define EMMC_CMD6 6	  /* SWITCH */
#define EMMC_CMD7 7	  /* SELECT/DESELECT_CARD */
#define EMMC_CMD8 8	  /* SEND_EXT_CSD */
#define EMMC_CMD9 9	  /* SEND_CSD */
#define EMMC_CMD10 10 /* SEND_CID */
#define EMMC_CMD11 11 /* READ_DAT_UNTIL_STOP */
#define EMMC_CMD12 12 /* STOP_TRANSMISSION */
#define EMMC_CMD13 13 /* SEND_STATUS */
#define EMMC_CMD14 14 /* BUSTEST_R */
#define EMMC_CMD15 15 /* GO_INACTIVE_STATE */
#define EMMC_CMD16 16 /* SET_BLOCKLEN */
#define EMMC_CMD17 17 /* READ_SINGLE_BLOCK */
#define EMMC_CMD18 18 /* READ_MULTIPLE_BLOCK */
#define EMMC_CMD19 19 /* BUSTEST_W */
#define EMMC_CMD20 20 /* WRITE_DAT_UNTIL_STOP */
#define EMMC_CMD21 21 /* SEND_TUNING_BLOCK (HS200) */
#define EMMC_CMD23 23 /* SET_BLOCK_COUNT */
#define EMMC_CMD24 24 /* WRITE_BLOCK */
#define EMMC_CMD25 25 /* WRITE_MULTIPLE_BLOCK */
#define EMMC_CMD26 26 /* PROGRAM_CID */
#define EMMC_CMD27 27 /* PROGRAM_CSD */
#define EMMC_CMD31 31 /* SEND_WRITE_PROT_TYPE */
#define EMMC_CMD32 32 /* TAG_SECTOR_START */
#define EMMC_CMD33 33 /* TAG_SECTOR_END */
#define EMMC_CMD34 34 /* UNTAG_SECTOR */
#define EMMC_CMD35 35 /* TAG_ERASE_GROUP_START */
#define EMMC_CMD36 36 /* TAG_ERASE_GROUP_END */
#define EMMC_CMD37 37 /* UNTAG_ERASE_GROUP */
#define EMMC_CMD38 38 /* ERASE */
#define EMMC_CMD39 39 /* FAST_IO */
#define EMMC_CMD40 40 /* GO_IRQ_STATE */
#define EMMC_CMD49 49 /* SET_TIME */
#define EMMC_CMD55 55 /* APP_CMD */
#define EMMC_CMD56 56 /* GEN_CMD */

/* eMMC 5.0+ commands */
#define EMMC_CMD58 58 /* READ_OCR */
#define EMMC_CMD59 59 /* CRC_ON_OFF */

/* Command argument bits */
#define EMMC_ARG_SWITCH_ACCESS_SHIFT 24
#define EMMC_ARG_SWITCH_INDEX_SHIFT 16
#define EMMC_ARG_SWITCH_VALUE_SHIFT 8
#define EMMC_ARG_SWITCH_CMDSET_SHIFT 0

#define EMMC_SWITCH_MODE_CMDSET 0x00
#define EMMC_SWITCH_MODE_SET_BITS 0x01
#define EMMC_SWITCH_MODE_CLEAR_BITS 0x02
#define EMMC_SWITCH_MODE_WRITE_BYTE 0x03

/* EXT_CSD indices for CMD6 SWITCH command */
#define EXT_CSD_CMD_SET_REV 189
#define EXT_CSD_CMD_SET 191
#define EXT_CSD_POWER_CLASS 187
#define EXT_CSD_HS_TIMING 185
#define EXT_CSD_BUS_WIDTH 183
#define EXT_CSD_ERASED_MEM_CONT 181
#define EXT_CSD_PARTITION_CONFIG 179
#define EXT_CSD_BOOT_CONFIG_PROT 178
#define EXT_CSD_BOOT_BUS_CONDITIONS 177
#define EXT_CSD_ERASE_GROUP_DEF 175
#define EXT_CSD_FW_CONFIG 169
#define EXT_CSD_RPMB_SIZE_MULT 168
#define EXT_CSD_WR_REL_SET 167
#define EXT_CSD_WR_REL_PARAM 166
#define EXT_CSD_RST_N_FUNCTION 162
#define EXT_CSD_PARTITIONING_SUPPORT 160
#define EXT_CSD_MAX_ENH_SIZE_MULT 157
#define EXT_CSD_PARTITIONS_ATTRIBUTE 156
#define EXT_CSD_PARTITION_SETTING_COMPLETED 155
#define EXT_CSD_GP_SIZE_MULT 143
#define EXT_CSD_ENH_SIZE_MULT 140
#define EXT_CSD_ENH_START_ADDR 136
#define EXT_CSD_SEC_BAD_BLK_MGMNT 134
#define EXT_CSD_TCASE_SUPPORT 132
#define EXT_CSD_PERIODIC_WAKEUP 131
#define EXT_CSD_PROGRAM_CID_CSD_DDR_SUPPORT 130
#define EXT_CSD_VENDOR_SPECIFIC_FIELD 64
#define EXT_CSD_NATIVE_SECTOR_SIZE 63
#define EXT_CSD_USE_NATIVE_SECTOR 62
#define EXT_CSD_DATA_SECTOR_SIZE 61
#define EXT_CSD_INI_TIMEOUT_EMU 60
#define EXT_CSD_CLASS_6_CTRL 59
#define EXT_CSD_DYNCAP_NEEDED 58
#define EXT_CSD_EXCEPTION_EVENTS_CTRL 56
#define EXT_CSD_EXCEPTION_EVENTS_STATUS 54
#define EXT_CSD_EXT_PARTITIONS_ATTRIBUTE 52
#define EXT_CSD_CONTEXT_CONF 37
#define EXT_CSD_PACKED_COMMAND_STATUS 36
#define EXT_CSD_PACKED_FAILURE_INDEX 35

/* HS_TIMING values */
#define EXT_CSD_TIMING_LEGACY 0x00
#define EXT_CSD_TIMING_HS 0x01
#define EXT_CSD_TIMING_HS200 0x02
#define EXT_CSD_TIMING_HS400 0x03

/* Enhanced Strobe fields */
#define EXT_CSD_STROBE_SUPPORT 184	 /* Enhanced strobe support register */
#define EXT_CSD_ENHANCED_STROBE 0x01 /* Enhanced strobe enable bit */

/* BUS_WIDTH values */
#define EXT_CSD_BUS_WIDTH_1 0x00
#define EXT_CSD_BUS_WIDTH_4 0x01
#define EXT_CSD_BUS_WIDTH_8 0x02
#define EXT_CSD_DDR_BUS_WIDTH_4 0x05
#define EXT_CSD_DDR_BUS_WIDTH_8 0x06

/* PARTITION_CONFIG values */
#define EXT_CSD_PARTITION_ACCESS_MASK 0x07
#define EXT_CSD_BOOT_PARTITION_ENABLE_MASK 0x38
#define EXT_CSD_BOOT_ACK_ENABLE 0x40

/* Card status bits (R1 response) */
#define EMMC_R1_OUT_OF_RANGE (1U << 31)
#define EMMC_R1_ADDRESS_ERROR (1U << 30)
#define EMMC_R1_BLOCK_LEN_ERROR (1U << 29)
#define EMMC_R1_ERASE_SEQ_ERROR (1U << 28)
#define EMMC_R1_ERASE_PARAM (1U << 27)
#define EMMC_R1_WP_VIOLATION (1U << 26)
#define EMMC_R1_CARD_IS_LOCKED (1U << 25)
#define EMMC_R1_LOCK_UNLOCK_FAILED (1U << 24)
#define EMMC_R1_COM_CRC_ERROR (1U << 23)
#define EMMC_R1_ILLEGAL_COMMAND (1U << 22)
#define EMMC_R1_CARD_ECC_FAILED (1U << 21)
#define EMMC_R1_CC_ERROR (1U << 20)
#define EMMC_R1_ERROR (1U << 19)
#define EMMC_R1_UNDERRUN (1U << 18)
#define EMMC_R1_OVERRUN (1U << 17)
#define EMMC_R1_CID_CSD_OVERWRITE (1U << 16)
#define EMMC_R1_WP_ERASE_SKIP (1U << 15)
#define EMMC_R1_CARD_ECC_DISABLED (1U << 14)
#define EMMC_R1_ERASE_RESET (1U << 13)
#define EMMC_R1_STATE_MASK (0x0F << 9)
#define EMMC_R1_READY_FOR_DATA (1U << 8)
#define EMMC_R1_SWITCH_ERROR (1U << 7)
#define EMMC_R1_EXCEPTION_EVENT (1U << 6)
#define EMMC_R1_APP_CMD (1U << 5)

#define EMMC_R1_STATE_SHIFT 9
#define EMMC_R1_ERROR_MASK 0xFDF98008U

/* OCR register bits */
#define EMMC_OCR_VDD_165_195 (1U << 7)
#define EMMC_OCR_VDD_20_21 (1U << 8)
#define EMMC_OCR_VDD_21_22 (1U << 9)
#define EMMC_OCR_VDD_22_23 (1U << 10)
#define EMMC_OCR_VDD_23_24 (1U << 11)
#define EMMC_OCR_VDD_24_25 (1U << 12)
#define EMMC_OCR_VDD_25_26 (1U << 13)
#define EMMC_OCR_VDD_26_27 (1U << 14)
#define EMMC_OCR_VDD_27_28 (1U << 15)
#define EMMC_OCR_VDD_28_29 (1U << 16)
#define EMMC_OCR_VDD_29_30 (1U << 17)
#define EMMC_OCR_VDD_30_31 (1U << 18)
#define EMMC_OCR_VDD_31_32 (1U << 19)
#define EMMC_OCR_VDD_32_33 (1U << 20)
#define EMMC_OCR_VDD_33_34 (1U << 21)
#define EMMC_OCR_VDD_34_35 (1U << 22)
#define EMMC_OCR_VDD_35_36 (1U << 23)
#define EMMC_OCR_SECTOR_MODE (1U << 30)
#define EMMC_OCR_CARD_POWER_UP (1U << 31)

#endif /* EMMC_CMD_H */
